#!/usr/bin/python3
##
## EPITECH PROJECT, 2024
## bombyx
## File description:
## 
##
import math
import sys
if (len(sys.argv) < 2 or len(sys.argv) > 4):
    exit(84)
if (len(sys.argv) == 2):
    if (sys.argv[1] == "-h"):
        print("USAGE")
        print("    ./106bombyx n [k | i0 i1]")
        print("DESCRIPTION")
        print("    n       number of first generation individuals")
        print("    k       growth rate from 1 to 4")
        print("    i0      initial generation (included)")
        print("    i1      final generation (included)")
        exit(0)
    exit(84)
if (len(sys.argv) == 3):
    nb = 1
    n = sys.argv[1]
    k = sys.argv[2]
    if (k[0] == '.'):
        exit(84)
    if (n[0] == '.'):
        exit(84)
    for i in n:
        if (i == '.'):
            continue
        if (i < '0' or i > '9'):
            exit(84)
    for i in k:
        if (i == '.'):
            continue
        if (i < '0' or i > '9'):
            exit(84)
    n = float(n)
    k = float(k)
    if (k < 1 or k > 4):
        exit(84)
    while (nb <= 100):
        print(f"{nb} {n:.2f}")
        n = k * n * ((1000 - n) / 1000)
        nb+= 1



if (len(sys.argv) == 4):
    nb = 1
    n = sys.argv[1]
    i0 = sys.argv[2]
    i1 = sys.argv[3]
    if (n[0] == '.'):
        exit(84)
    for i in n:
        if (i == '.'):
            continue
        if (i < '0' or i > '9'):
            exit(84)
    for i in i0:
        if (i < '0' or i > '9'):
            exit(84)
    for i in i1:
        if (i < '0' or i > '9'):
            exit(84)
    k = 1
    n = int(n)
    i0 = int(i0)
    i1 = int(i1)
    if (i1 <= i0):
        exit (84)
    if (i0 < 1):
        exit(84)
    while (k <= 4):
        x1 = n
        for i in range(2, i1 + 1):
            x1 = (k * x1 * ((1000 - x1) / 1000))
            if (i >= i0):
                print(f"{k:.2f} {x1:.2f}")
        k += 0.01