.TH 42sh 1 "Avril 2025" "Version 1.0" "Manual page"

.SH NAME
\t./mysh - Custom shell made for an EPITECH project.

.SH SYNOPSIS
\tmysh [OPTIONS]

.SH DESCRIPTION
\tmysh is a command language interpreter usable both as an interactive login language

.SH BUILT IN
\tcd [PATH] - navigate into the computer

\tenv - display the current environment

\tsetenv [NAME] [OPTIONS] - add a new environment variable

\tunsetenv [NAME] - delete the environement variable

\texit [NUMBER] - exit with an exit code

\tcolor [PROMPT] [COLOR] - change prompt color

\talias [NAME] [OTIONS] - add a new alias

\tunalias [NAME] - remove an already existing alias

.SH SEPARATOR
\t; - separator to execute multiple command

\t&& - separator to execute multiple command if the command exit code is > 0 stop

\t|| - separator to execute multiple command if the command exit code is = 0 stop

\t| - pipe to execute a command in another one

\t\> - redirect the exit of a command into a new file

\t\>> - redirect the exit of a command into a file

\t< - redirect the content into a command

.SH DELIMITOR
\t" " - delimitor to make multi word command

\t' ' - delimitor to make multi word command but without local and environement variables

\t` ` - delimitor to execute a command in another one

\t( ) - delimitor to execute a command in another shell
.SH
.SH AUTHOR
\t| HEIMMER Julian | MALFILATRE Gauthier | MARTIN Hugo | MARCOT Romain | MACIEJEWSKI Pierre |
