#!/usr/bin/python3
import math
import sys

def str_der(a, r):
    result = math.sqrt(r*r - a*a)
    return result

def harmo_mean(mean, value, number):
    if (value == 0):
        exit(84)
    result = number / mean
    result = (number + 1) / (result + (1 / value))
    return result
    

def sqrt_mean(n,r, x):
    result = math.sqrt(1/(n+1) * (n*r**2 + x**2))
    return result

def a_mean(mean, value, number):
    result = mean * number
    result = result + value
    result = result / (number + 1)
    return result

if (len(sys.argv) != 5):
    exit (84)
for i in range (1, 5):
    for j in sys.argv[i]:
        if ((j < '0' or j > '9') and j != '-'):
            exit (84)
n = int(sys.argv[1])
if (n < 0):
    exit(84)
a = int(sys.argv[2])
h = int(sys.argv[3])
sd = int(sys.argv[4])
r = math.sqrt(sd * sd + a * a)

while (1):
    x = input ("Enter next value: ")
    if (x == 'END'):
        exit (0)
    for j in x:
        if ((j < '0' or j > '9') and j != '-' and j != '.'):
            exit (84)
    x = float (x)
    a = a_mean(a, x, n)
    h = harmo_mean(h, x, n)
    r = sqrt_mean(n, r, x)
    sd = str_der(a, r)
    n = n + 1
    print(f"    Number of values:   {n}")
    print(f"    Standard deviation: {sd:.2f}")
    print(f"    Arithmetic mean:    {a:.2f}")
    print(f"    Root mean square:   {r:.2f}")
    print(f"    Harmonic mean:      {h:.2f}")
    print()
